# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20160217_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='target',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='like_target', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
