# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts_for_this_tag', to='post.Tag'),
        ),
    ]
