# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160209_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='best_qoute',
            new_name='best_quote',
        ),
    ]
