# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20160209_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.CharField(default=b'en', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.CharField(default=b'slate', max_length=40),
        ),
    ]
