# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_achievement'),
        ('authentication', '0005_auto_20160212_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='achievements',
            field=models.ManyToManyField(to='post.Achievement'),
        ),
    ]
