# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160219_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
