# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20160219_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 19, 4, 7, 3, 29180, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
