# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_account_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.TextField(blank=True),
        ),
    ]
