# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.TextField(blank=True),
        ),
    ]
