# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_account_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='now',
        ),
    ]
